
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { BookingProvider } from "@/context/BookingContext";
import { PaymentProvider } from "@/context/PaymentContext";
import { ReviewProvider } from "@/context/ReviewContext";
import { AdminProvider } from "@/context/AdminContext";
import GoogleMapsWrapper from "@/components/googleComponents/GoogleMapsWrapper";
import RouteLoader from "@/components/Loader/RouteLoader";
import OfflineNotice from "@/components/offline/OfflineNotice";
import { AuthProvider } from "@/context/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
     
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <BookingProvider>
            <PaymentProvider>
              <ReviewProvider>
                <AdminProvider>
                  <GoogleMapsWrapper>
                    <RouteLoader />
                    <OfflineNotice/>
         
                  {children}
                  </GoogleMapsWrapper>
                </AdminProvider>
              </ReviewProvider>
            </PaymentProvider>
          </BookingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
